### ISSUE TITLE
Unused Variables / Declare with `const`

### ISSUE THREAD

**Issue by karlhorky** [julialearnscoding/meme-scraper#5]
There are some variables that are either declared with `var` or just unused:

https://github.com/julialearnscoding/meme-scraper/blob/749920f0ae455dfadfaecdd8bfed76b4205ccc8f/index.js#L34-L35

https://github.com/julialearnscoding/meme-scraper/blob/749920f0ae455dfadfaecdd8bfed76b4205ccc8f/index.js#L105

You can see the unused variables in the editor (the names are a bit dimmer than the other ones):

![Screen Shot 2019-09-27 at 12 00 26](https://user-images.githubusercontent.com/1935696/65761454-17244700-e11f-11e9-999d-dee1a9d6e2f2.png)

![Screen Shot 2019-09-27 at 12 00 37](https://user-images.githubusercontent.com/1935696/65761464-1d1a2800-e11f-11e9-9de0-59c7b3677de5.png)

**Comment by julialearnscoding** [comment]
fixed in a85be4b2a3290647ff9f68ab13a9dab01476503a

**Comment by karlhorky** [comment]
Nice one, thanks!
