### ISSUE TITLE
Ignore images from git

### ISSUE THREAD

**Issue by karlhorky** [julialearnscoding/meme-scraper#6]
Using [your `.gitignore` file](https://github.com/julialearnscoding/meme-scraper/blob/master/.gitignore) you can ignore the images so that they don't show up on GitHub.

In order to do this, you can try googling "gitignore images".

Otherwise they will be on GitHub and will be downloaded when people download your program:

![Screen Shot 2019-09-27 at 12 27 07](https://user-images.githubusercontent.com/1935696/65762920-73d53100-e122-11e9-800f-758e076f64ac.png)

To ignore the things that are downloaded by the program is often considered best practice.

**Comment by julialearnscoding** [comment]
fixed in 9ab42fe6586bc9440a3d12b888b8aefc8bb38c10

**Comment by karlhorky** [comment]
@julialearnscoding awesome, killing it today!
